### ISSUE TITLE
关于可通过创建不同应用程序来执行不同屏幕组合预设的提议

### ISSUE THREAD

**Issue by Hyaeve** [qiin2333/qiin.github.io#1]
在以往的sunshine版本中，如若实现扩展或熄屏或串流主屏，通过sunshine原有配置，这都是简单易行的。然而对于兼顾办公需求和游戏需求的人群来说，想要实现多种屏幕组合预设，通过更改sunshine原本设置来回切换，是麻烦的；而通过外部工具，在不同应用程序中添加屏幕执行命令，是可以实现的，然而就本人经验来说，这样的方法会触发hdr bug，同样是不优雅的。期待sunshine能够内置实现多种屏幕组合的那一天。

**Comment by qiin2333** [comment]
切换屏幕的HDR问题已经解决了，另外问题提错了项目，先关闭了
